# Generated by Django 5.0.4 on 2024-05-31 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotofacil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_id', models.IntegerField()),
                ('concurso', models.IntegerField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
