# Generated by Django 5.0.4 on 2024-05-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotofacil', '0002_userpicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicks',
            name='concurso',
            field=models.CharField(max_length=20),
        ),
    ]
