# Generated by Django 5.0.4 on 2024-05-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotofacil', '0003_alter_userpicks_concurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicks',
            name='concurso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userpicks',
            name='pick_id',
            field=models.CharField(max_length=40),
        ),
    ]
