# Generated by Django 5.0.4 on 2024-05-31 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lotofacil', '0004_alter_userpicks_concurso_alter_userpicks_pick_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpicks',
            name='id',
        ),
        migrations.AlterField(
            model_name='userpicks',
            name='pick_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
