# Generated by Django 5.0.4 on 2024-05-31 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotofacil', '0006_userpix_delete_userpicks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPix',
            new_name='UserPicks',
        ),
    ]
