# Generated by Django 5.0.4 on 2024-05-31 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lotofacil', '0007_rename_userpix_userpicks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpicks',
            old_name='bet_number',
            new_name='play_number',
        ),
    ]
